services:

  # Let's create our background worker
  - type: worker
    name: sidekiq-worker
    env: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -r ./main.rb
    autoDeploy: false
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
